# Numpy

## Import

In [1]:
import numpy as np

Zor ama velev ki numpy yüklü değil.

!pip install numpy

Komutu ile ekleyebilirsin. Sonrasında import komutunu tekrar yazıver. 
____
Hala bir sorun varsa **[BURAYA TIKLA](https://www.scipy.org/install.html)**. Numpy'ın kendi sayfasındaki kurulum rehberine gideceksin.

___
Numpy'ın içinden geçmek için ---> [[Bana TIK](https://docs.scipy.org/doc/numpy-1.15.0/index.html)]

## Numpy Array

In [5]:
list = [1,2,3]
list

[1, 2, 3]

In [3]:
type(list)

list

In [6]:
array = np.array(list)

In [4]:
type(array)

numpy.ndarray

In [10]:
matrix_1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(matrix_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(type(matrix_1))
print(matrix_1)

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [14]:
matrix_1 = np.array(matrix_1)
matrix_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

___
___

## Hazır Metotlar

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [18]:
matrix_2 = np.arange(1,10).reshape(3,3)
matrix_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.linspace(0,100,35)

array([ 0.        ,  0.29411765,  0.58823529,  0.88235294,  1.17647059,
        1.47058824,  1.76470588,  2.05882353,  2.35294118,  2.64705882,
        2.94117647,  3.23529412,  3.52941176,  3.82352941,  4.11764706,
        4.41176471,  4.70588235,  5.        ,  5.29411765,  5.58823529,
        5.88235294,  6.17647059,  6.47058824,  6.76470588,  7.05882353,
        7.35294118,  7.64705882,  7.94117647,  8.23529412,  8.52941176,
        8.82352941,  9.11764706,  9.41176471,  9.70588235, 10.        ])

In [31]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

___
___

## Random

In [32]:
np.random.rand(4)

array([0.66097141, 0.81699133, 0.5244013 , 0.1565036 ])

In [33]:
np.random.rand(3,3)

array([[0.24955577, 0.29118721, 0.42693301],
       [0.47647709, 0.73051341, 0.55061046],
       [0.360755  , 0.72725946, 0.89816014]])

In [34]:
np.random.randn(4)

array([ 0.25722182,  1.00006098,  0.77456344, -1.26617155])

In [36]:
np.random.randn(4,4)

array([[ 0.94651241,  1.15604105,  0.72152341,  1.10749387],
       [-2.54542465, -0.21816492, -0.60076301,  0.70631071],
       [ 1.76935063, -0.20294639, -0.15544254,  0.83716003],
       [ 0.09732809,  0.55062219,  0.06878472, -0.91124342]])

In [43]:
np.random.randint(0,1)

0

In [44]:
np.random.randint(1,100)

13

In [45]:
np.random.randint(1,9,9)

array([8, 6, 2, 6, 2, 3, 4, 8, 6])

In [46]:
np.random.seed(99)
np.random.rand(4)

array([0.67227856, 0.4880784 , 0.82549517, 0.03144639])

In [50]:
np.random.seed(99)
np.random.rand(5)

array([0.67227856, 0.4880784 , 0.82549517, 0.03144639, 0.80804996])

In [51]:
np.random.rand(5)

array([0.56561742, 0.2976225 , 0.04669572, 0.9906274 , 0.00682573])

___
___

## Max Min

In [56]:
array = np.arange(20)

In [57]:
array.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
rand_array = np.random.randint(0,100,15)
rand_array

array([73, 32, 21, 41, 99, 19, 22, 26, 50, 59,  5, 12, 96, 53, 91])

In [60]:
rand_array.max()

99

In [61]:
rand_array.argmax()

4

In [62]:
rand_array.min()

5

In [63]:
rand_array.argmin()

10

___
___

## Shape & Type

In [64]:
array.shape

(20,)

In [67]:
array.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [68]:
array.reshape(1,20).shape

(1, 20)

In [69]:
array.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [70]:
array.reshape(20,1).shape

(20, 1)

In [71]:
type(array)

numpy.ndarray

In [72]:
array.dtype

dtype('int32')

In [75]:
array_2 = np.linspace(0,4,10).reshape(2,5)
array_2

array([[0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778],
       [2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ]])

In [76]:
array_2.dtype

dtype('float64')

___
___

## İşlemler

In [111]:
arr_2d = np.array(([10,20,30],[40,50,60],[70,80,90]))

In [112]:
arr_2d+5

array([[15, 25, 35],
       [45, 55, 65],
       [75, 85, 95]])

In [96]:
arr_2d-9

array([[ 1, 11, 21],
       [31, 41, 51],
       [61, 71, 81]])

In [92]:
arr_2d/5

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [93]:
arr_2d*4

array([[ 40,  80, 120],
       [160, 200, 240],
       [280, 320, 360]])

In [97]:
arr_2d**2

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]], dtype=int32)

In [107]:
arr_2d/arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [108]:
1/arr_2d

array([[0.1       , 0.05      , 0.03333333],
       [0.025     , 0.02      , 0.01666667],
       [0.01428571, 0.0125    , 0.01111111]])

In [109]:
0/arr_2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
arr_2d/0

<ipython-input-110-ba585203d08e>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_2d/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [113]:
np.sqrt(arr_2d)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [114]:
np.sin(arr_2d)

array([[-0.54402111,  0.91294525, -0.98803162],
       [ 0.74511316, -0.26237485, -0.30481062],
       [ 0.77389068, -0.99388865,  0.89399666]])

In [115]:
np.exp(arr_2d)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

In [117]:
np.log(arr_2d)

array([[2.30258509, 2.99573227, 3.40119738],
       [3.68887945, 3.91202301, 4.09434456],
       [4.24849524, 4.38202663, 4.49980967]])

___
___

## İndex

In [77]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr[9]

9

In [79]:
arr[2:6]

array([2, 3, 4, 5])

In [80]:
arr[2:6] = 99
arr

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9])

In [83]:
arr = np.arange(0,11)

In [87]:
arr_part = arr[2:6]
arr_part

array([2, 3, 4, 5])

In [88]:
arr_part[:] = 99
arr_part

array([99, 99, 99, 99])

In [89]:
arr

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [90]:
copy_arr = arr.copy()
copy_arr

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [91]:
arr_2d = np.array(([10,20,30],[40,50,60],[70,80,90]))

In [98]:
arr_2d[2]

array([70, 80, 90])

In [99]:
arr_2d[2][1]

80

In [100]:
arr_2d[2,1]

80

In [101]:
arr_2d[:1,1:]

array([[20, 30]])

In [102]:
arr_2d[2,:]

array([70, 80, 90])

In [103]:
arr_2d <55

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [105]:
arr_2d[arr_2d<55]

array([10, 20, 30, 40, 50])

___
___

## İstatistiksel İfadeler

In [120]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
arr.sum()

45

In [122]:
arr_2d.sum()

450

In [123]:
arr.mean()

4.5

In [124]:
arr_2d.mean()

50.0

In [125]:
arr.min()

0

In [126]:
arr.std()

2.8722813232690143

In [127]:
arr.var()

8.25

___
___

## Eksen (axis)

In [128]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [129]:
arr_2d.sum(axis=0)
# axis=0 Satırları seçer

array([120, 150, 180])

In [130]:
arr_2d.sum(axis=1)
# axis=1 Sütunları seçer

array([ 60, 150, 240])

___
___

# https://www.youtube.com/watch?v=WbNYbxdW3mk